create table "public"."InventoryItems" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "container" text not null,
    "reference" text not null,
    "quantity" numeric not null,
    "observations" text not null
);


alter table "public"."InventoryItems" enable row level security;

CREATE UNIQUE INDEX "InventoryItems_pkey" ON public."InventoryItems" USING btree (id);

alter table "public"."InventoryItems" add constraint "InventoryItems_pkey" PRIMARY KEY using index "InventoryItems_pkey";

create policy "Enable insert for authenticated users only"
on "public"."InventoryItems"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."InventoryItems"
as permissive
for select
to public
using (true);



