export const supabaseUrl = "https://olhatqrwnaphyxphdmzg.supabase.co";
export const supabaseKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9saGF0cXJ3bmFwaHl4cGhkbXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTY2NzA1ODEsImV4cCI6MjAxMjI0NjU4MX0.A8F8Y-KQGZclxZxUHRSL43HOy7KFKORGYovyDxvmY34";
